name: UI Deploy Workflow
on:
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    strategy:
      matrix:
        node_version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          version: ${{ matrix.node_version }}

      - name: Install Amplify CLI & Deploying Project
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REACT_APP_DATA_PICKER_MIN_DATE: ${{ secrets.REACT_APP_TITLE }}
        run: |
          npm install
          npm install -g @aws-amplify/cli --unsafe-perm=true
          bash scripts/init.sh
          amplify publish --yes
